### ISSUE TITLE
Github Login is not shown for Deployed Site's Admin Page 

### ISSUE THREAD

**Issue by caseyjkey** [unfolding-io/nebulix#11]
Locally, the admin page says "Login with Github", and then I created a page and saw it committed to the repo. However, when I visit the Netlify deployed website's admin page, the login button says "Login" and then saving entries does not persist after leaving the editing page.

It is also taking around 110 seconds for `npm run dev` to execute.

Here is my configuration, should I include my github user or just the repo name?

```
  backend: {
    name: "github",
    repo: "caseyjkey/nebulix-portfolio",
    commit_messages: {
	create: 'Create {{collection}} "{{slug}}"',
	update: 'Update {{collection}} "{{slug}}"',
	delete: 'Delete {{collection}} "{{slug}}"',
	uploadMedia: 'Upload "{{path}}"',
	deleteMedia: 'Delete "{{path}}"'
     }
  },
  search: "true",
  media_folder: "src/assets",
  public_folder: "/src/assets",
  media_library: {
    max_file_size: 2012000,
    folder_support: true,
  },
  collections: [page, post, project, product, menu, settings],
};
```

**Comment by preetamslot** [comment]
@caseyjkey 
GitHub takes a bit more work, GitLab works almost out of the box.

Here the docs from Static CMS:
https://www.staticcms.org/docs/github-backend

```
Because Github requires a server for authentication, Netlify facilitates basic GitHub authentication.

To enable basic GitHub authentication:

Follow the authentication provider setup steps in the [Netlify docs](https://www.netlify.com/docs/authentication-providers/#using-an-authentication-provider).
```

If you are using netlify, you can also use git gateway
https://www.staticcms.org/docs/git-gateway-backend

**Comment by jpollone** [comment]
@preetamslot Do you have clients that want control of what and when they publish without using a full CMS?

For my personal site, I enjoy using StaticCMS locally and when I'm satisfied, I'll commit/push to Github. 

When I build my son's site, I'll just have him send me the content and I'll deploy it in the same way as mine. It will be easier to not need to worry about who can do what. 😀

**Comment by preetamslot** [comment]
@jpollone Well most clients want a full CMS and do their own updates, 
I have some clients who dont have the time and they send me the content and the I'll publish it.

I choose the CMS for the client, like Static CMS is more for an advanced user, If I have a client less advanced, I make use of Storyblok. The downside is that the editor of storyblok works best with an SSR setup, so to make this work I have to make 2 deploys, one SSR and one SSG for the live site. an example of this is https://www.roorda.nl/.
