### ISSUE TITLE
Page Load Issue On Chrome 

### ISSUE THREAD

**Issue by mubasherkhan** [unfolding-io/nebulix#13]
On chrome below error occurs while navigating to pages. After reloading page load successfully. This issue is occurring on both local and live build. 
```
Aw, Snap!
Something went wrong while displaying this webpage.
Error code: 11
```

**Comment by preetamslot** [comment]
This is unexpected.
do you have an url for me so I can check it out?

**Comment by mubasherkhan** [comment]
Updated the browser ,now it is working ok. 
Before Update, When I clicked on any other link like shop, blog it showed below. On reloading the page it redirect to the desired page.  
`Aw, Snap!
Something went wrong while displaying this webpage.
Error code: 11`
