### ISSUE TITLE
Unable to change the logo 

### ISSUE THREAD

**Issue by getofmeland** [unfolding-io/nebulix#17]
I have tried to change the logo to an SVG created in Canva, but it never renders on the build.  

I have tried a complex based image but also a very basic text image.

**Comment by preetamslot** [comment]
Hi @getofmeland, can you share the svg and let me know what you mean with "it never renders on the build"?

Thanks

**Comment by getofmeland** [comment]
![logoold](https://github.com/unfolding-io/nebulix/assets/67956370/1ce4520d-82fa-4909-abb0-54d17067c380)
![Cloud Security Insider (1)](https://github.com/unfolding-io/nebulix/assets/67956370/04751483-c754-4f4c-955c-bc3dfd5ff6cc)

I have tried both of these and they never render.   I apologise as I am just trying to learn Astro and the capabilities and came across your awesome template and wanted to make it work for me.

**Comment by preetamslot** [comment]
Your image is not vector based :(
if you look at the source, it is based on pixel images embedded in an SVG.

![image](https://github.com/unfolding-io/nebulix/assets/5420582/2578619a-23c8-43a9-ace7-048899168a4d)

You can always test and optimize SVG here: https://jakearchibald.github.io/svgomg/
