### ISSUE TITLE
Cannot find module '@vueuse/core' imported from '/home/bob/astro/demo-nebulix/src/components/navigation/NavMobile.vue'

### ISSUE THREAD

**Issue by BorisTherin** [unfolding-io/nebulix#19]
![image](https://github.com/unfolding-io/nebulix/assets/89749441/8c2ed4a9-282c-453a-aec7-1da7204b4884)

![image](https://github.com/unfolding-io/nebulix/assets/89749441/84429dbc-d7f8-4dbd-b926-f9fcbe8581c7)

added it myself `pnpm add @vueuse/core' a it works again.

**Comment by BorisTherin** [comment]
sry, my bad.

i used pnpm and when using npm, it works fine.
didnt know pnpm could have such an issue

**Comment by preetamslot** [comment]
I have added "@vueuse/core" to the packag.json. I think with NPM it automatically gets installed by "@vueuse/components". 
Thanks for the heads up
