### ISSUE TITLE
Console.log error

### ISSUE THREAD

**Issue by FutureBuddha** [unfolding-io/nebulix#21]
The theme displays an error in the console's inspect window, as shown below:
![image](https://github.com/unfolding-io/nebulix/assets/149382049/4cd96774-847a-44ea-b549-26d9efa9686e)
While this is not a major issue, the theme no longer scores a hundred on [PageSpeed Insights](https://pagespeed.web.dev/) under 'Best Practices.'

![image](https://github.com/unfolding-io/nebulix/assets/149382049/2e2c42a0-c97e-4ba0-a9cd-c13f48058d74)

**Comment by preetamslot** [comment]
Hi @FutureBuddha,
I think this is astro-compress related, for now set HTML to false in the astro.config.
Before the settings I used worked, but not anymore:(.

I have updated the config file.
```
compress({
      CSS: true,
      HTML: false,
      Image: false,
      JavaScript: true,
      SVG: true,
    }),
```
Let me know if this fixes your issue.

**Comment by FutureBuddha** [comment]
Yes thank you.
A lot of the optimization from Astro goes missing like that, but a least it look nice on the page speed test ;)

**Comment by preetamslot** [comment]
Not Really a big problem,
Astro components are compressed by default, only HTML of Vue components are not compressed.
Before with the html compression config, I never head Hydration issues, and it took me some time to find the right configuration. But something small as a missing comment can already give an hydration error. :(

If you want HTML compression on, I would advice to check out the issues on astro-compress and see if there is a solution.
https://github.com/astro-community/AstroCompress/issues?q=is%3Aissue+vue
