### ISSUE TITLE
Postmark configuration

### ISSUE THREAD

**Issue by getofmeland** [unfolding-io/nebulix#31]
### Discussed in https://github.com/unfolding-io/nebulix/discussions/30

<div type='discussions-op-text'>

<sup>Originally posted by **getofmeland** January 16, 2024</sup>
Hi All, 

I am trying to get Postmark configured on my version of the site, when I try to submit an email I get the following message:

We could not send your message. Please try again.

I have checked my configuration and server configuration in the env and that all seems to be ok.   When I monitor the edge function log, I am getting an alert that : Jan 16, 03:51:55 PM: info   SLACK_TOKEN undefined 

So I am not even sure if its attempting to go via Postmark.

Has anyone else managed to get this working</div>

**Comment by preetamslot** [comment]
Hi @getofmeland,
can you conform your contact settings.
so run `npm run dev` and `npm run cms-proxy-server`
and go to:
http://localhost:4321/admin#/collections/config/entries/contact

what is the provider you see?
![image](https://github.com/unfolding-io/nebulix/assets/5420582/3979eb07-d8f6-49bd-ba74-ac914392cb20)

**Comment by getofmeland** [comment]
I see all 3 but Postmark is selected
![image](https://github.com/unfolding-io/nebulix/assets/67956370/a09e6c2c-de6b-432a-ad33-65976ad503c9)

I also have my postmark server api key listed in my .env file in the root

**Comment by preetamslot** [comment]
Postmark should work,
the `SLACK_TOKEN undefined` was just a console log on the slack endpoint.

Take a look at the response to see why postmark is not sending your email you can check your console if you are running `netlify dev` or if it is on netlify check the `edge functions` log

```
[contact-postmark] {
  ErrorCode: 412,
  Message: "While your account is pending approval, all recipient addresses must share the same domain as the 'F"... 143 more characters
```

**Comment by getofmeland** [comment]
Have tried Mailgun as well and I am getting literally the same message, and nothing in the edge functions logs either.

**Comment by preetamslot** [comment]
can you check the network response of the form submit?

**Comment by getofmeland** [comment]
So saying Mailgun configuration is missing from the .env file, I have checked my .env file and the configuration is there:

![image](https://github.com/unfolding-io/nebulix/assets/67956370/ee4b99f7-71ff-487f-84a6-d8e2b29b71a7)

**Comment by preetamslot** [comment]
Where are you hosting the site, netlify?

the error comes from an edge / deno function:

```

let {
  MAILGUN_API_KEY,
  MAILGUN_API_URL,
  MAILGUN_DOMAIN,
  FROM_EMAIL_ADDRESS,
  TO_EMAIL_ADDRESS,
} = Deno.env.toObject();

export default async (request, context) => {
  if (
    !MAILGUN_API_KEY ||
    !FROM_EMAIL_ADDRESS ||
    !TO_EMAIL_ADDRESS ||
    !MAILGUN_API_URL
  )
    return Response.json({
      error: "Missing MailGun configuration, please check your .env file.",
    });

```
Can you console.log the ` Deno.env.toObject()` to see if they are available?

**Comment by getofmeland** [comment]
Will have a look, the site is hosted with netlify.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by getofmeland** [comment]
Having made a change it appears the script for mailgun isn't picking up the Environmental Variables:

`Jan 20, 09:37:29 PM: info   [Object: null prototype] {Jan 20, 09:37:29 PM: info     CURRENCY: "GBP",Jan 20, 09:37:29 PM: info     MENU_SLUG: "menu",Jan 20, 09:37:29 PM: info     PORTFOLIO_SLUG: "work",Jan 20, 09:37:29 PM: info     DENO_DEPLOYMENT_ID: "Ami48YCgoOo9GaYA01Ipfvv6raPNIIheUFvkR2RX_nY=",Jan 20, 09:37:29 PM: info     NODE_VERSION: "18",Jan 20, 09:37:29 PM: info     WEBSITE_LANGUAGE: "en",Jan 20, 09:37:29 PM: info     DENO_REGION: "aws-eu-central-1",Jan 20, 09:37:29 PM: info     BLOG_SLUG: "blog",Jan 20, 09:37:29 PM: info     SHOP_SLUG: "shop",Jan 20, 09:37:29 PM: info     UNITS: "metric"Jan 20, 09:37:29 PM: info   }Jan 20, 09:44:39 PM: info   Environment variables: {Jan 20, 09:44:39 PM: info     MAILGUN_API_KEY: undefined,Jan 20, 09:44:39 PM: info     MAILGUN_API_URL: undefined,Jan 20, 09:44:39 PM: info     MAILGUN_DOMAIN: undefined,Jan 20, 09:44:39 PM: info     FROM_EMAIL_ADDRESS: undefined,Jan 20, 09:44:39 PM: info     TO_EMAIL_ADDRESS: undefinedJan 20, 09:44:39 PM: info   }`

**Comment by getofmeland** [comment]
So in addition to this, I added these into the Netlify Environmental Variables and they are pulled in... 

When I submit the form I now get a new error:

uncaught exception during edge function invocation

**Comment by getofmeland** [comment]
It appeared to be linked to the encode function, I have updated the script to as follows:

```
import { encodeBase64 } from "https://deno.land/std/encoding/base64.ts";

let {
  MAILGUN_API_KEY,
  MAILGUN_API_URL,
  MAILGUN_DOMAIN,
  FROM_EMAIL_ADDRESS,
  TO_EMAIL_ADDRESS,
} = Deno.env.toObject();

// Get the environment variables as an object
const envObject = Deno.env.toObject();

// Log the object to the console
console.log(envObject);


export default async (request, context) => {

  if (
    !MAILGUN_API_KEY ||
    !FROM_EMAIL_ADDRESS ||
    !TO_EMAIL_ADDRESS ||
    !MAILGUN_API_URL
  )
    return Response.json({
      error: "Missing MailGun configuration, please check your .env file.",
    });

  const { email, name, message, topicEmail } = await request.json();

  if (!email || email === "") return Response.json({ error: "Missing email" });
  const authHeader = "Basic " + encodeBase64(`api:${MAILGUN_API_KEY}`);

  const headers = {
    "Access-Control-Allow-Origin": "*",
    "Content-Type": "application/x-www-form-urlencoded",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "OPTIONS,POST,GET",
    Authorization: authHeader,
  };

  let payload = new URLSearchParams();

  payload.append("from", FROM_EMAIL_ADDRESS);
  payload.append("to", topicEmail ? topicEmail : TO_EMAIL_ADDRESS);
  payload.append("h:Reply-To", email);
  payload.append("subject", `Contact Form: ${name} ${email}`);
  payload.append("text", message); 
  try {
    const resp = await fetch(
      `${MAILGUN_API_URL}/v3/${MAILGUN_DOMAIN}/messages`,
      {
        method: "POST",
        headers: headers,
        body: payload,
      },
    );

    let response = await resp.json();

    return Response.json({
      statusCode: 200,
      status: resp?.ok ? "ok" : "error",
      body: "Your message was sent successfully! We'll be in touch.",
    });
  } catch (e) {
    console.log("ERROR:", e);
    return Response.json({
      statusCode: 400,
      status: "error",
      error: "Mailgun  error",
    });
  }
};
```

**Comment by preetamslot** [comment]
Thanks!
strange that encode works local but not on netlify.
I have updated the function.
