### ISSUE TITLE
Pagination issue when blog goes over multiple pages

### ISSUE THREAD

**Issue by getofmeland** [unfolding-io/nebulix#32]
When you have more than a single page of blog posts, there is an issue around the pagination buttons at the bottom.  They render the URL as "/blog/undefined//2"

Just looking to see if I can find a fix but logging as well

Example on my site: https://cloudsecurityinsider.com/blog/

**Comment by preetamslot** [comment]
I think it is fixed now, let me know if it works

**Comment by getofmeland** [comment]
Awesome that's all working 👍
