### ISSUE TITLE
Typo on Home Page

### ISSUE THREAD

**Issue by dmonahan24** [unfolding-io/nebulix#4]
Line 63 of /src/content/page/index.mdx - Multiple has a typo

Do I have permissions to create a branch and open PR?

**Comment by preetamslot** [comment]
Thanks! I have updated the content.

**Comment by dmonahan24** [comment]
Possibly another near line 20 of same file. Class for the Link component is "Optinal"

**Comment by preetamslot** [comment]
@dmonahan24, I am a dyslectic designer who likes to code, so I can imagine there will be some typo's in this repo.
Thanks for the pointers!
