### ISSUE TITLE
False blocking validation when using local backend

### ISSUE THREAD

**Issue by jpollone** [unfolding-io/nebulix#9]
**1. Steps to reproduce**

1. Start up local backend `npm run cms-proxy-server`
2. Create a new project entry
3. Complete the form with a few tags, title, seo, and image
4. Publish and then verify the page appears in the Work/Project area
5. Edit the page and add a add a project feature using the local backend
6. Click Publish Now

**2. Incorrect behavior**
The validation message "missing required field" appears but there is no other indication of a field missing on the UI. 

**3. Work-around**
Manually adding the project feature to the file works fine.:

```
features:
  - name: Year
    value: "2023"
```

**4. Additional**
These false validations occurs with several areas and I can report each individually, if preferred.

**5. Screenshot**
![nebulix-validation](https://github.com/unfolding-io/nebulix/assets/957276/1b2d9633-af34-4e5d-9a21-a3006ca34c12)

**Comment by preetamslot** [comment]
Hi @jpollone 
This was a StaticCMS bug: https://github.com/StaticJsCMS/static-cms/issues/931

They just made a fix in v 3.3.7.
I have updated the admin.it should work now.

You can also just find the css and js file of Static CMS in de admin page and change it from 3.3.0 to 3.3.7

**Comment by jpollone** [comment]
@preetamslot thanks for finding that. I had not used StaticCMS but it's a nice tool for me. I'm still learning what is available in Nebulix, Astro, and StaticCMS so I try to bounce between them to learn a bit more.
